apiVersion: v1
kind: PersistentVolume
metadata:
  name: subject-pv
  labels:
    pv.kubernetes.io/type: e2e-test
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/e2e/pvc-subject
    type: DirectoryOrCreate
  # 'Delete' is only supported inside /tmp
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
