apiVersion: k8up.io/v1
kind: PreBackupPod
metadata:
  name: mysqldump
spec:
  backupCommand: echo "BACKUP!"
  pod:
    spec:
      initContainers:
      - name: init
        image: mariadb
        imagePullPolicy: IfNotPresent
        command:
        - sleep
        - '20s'
      containers:
        - env:
            - name: USER
              value: dumper
            - name: PW
              value: topsecret
            - name: DB_HOST
              value: mariadb.example.com
          image: mariadb
          command:
            - sleep
            - infinity
          imagePullPolicy: IfNotPresent
          name: mysqldump
