apiVersion: v1
kind: Secret
metadata:
  name: backup-credentials
type: Opaque
stringData:
  username: myaccesskey
  password: mysecretkey
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-repo
type: Opaque
stringData:
  password: asdf
