---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: NodePort
  ports:
    - port: 9000
      name: minio-api-port
      targetPort: 9000
      protocol: TCP
    - port: 9001
      name: mini-browser-port
      targetPort: 9001
      protocol: TCP
  selector:
    app: minio
